  
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
####

name: Develpment-CI

on:
  push:
    branches: [ development ]

jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2


      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Step 4 - Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2      
          
      - name: Step 3 - Clean Maven TaxCalculator Project
        run: mvn -B clean --file pom.xml
        
      - name: Step 4 - Validate Maven TaxCalculator Project
        run: mvn -B validate --file pom.xml
          
      - name: Step 4 - Compile Maven TaxCalculator Project
        run: mvn -B compile --file pom.xml
          
          
  Test:
    runs-on: ubuntu-latest
    needs: [Build]

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2
      
      
    - name: Step 2 - Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Step 3 - Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2      
        
    - name: Step 4 - Test Maven TaxCalculator Project
      run: mvn -B test --file pom.xml
