# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build-Test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Steo 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2
      
      
    - name: Step 2 - Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Step 3 - Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2      
        
    - name: Step 4 - Build with Test Maven Project
      run: mvn -B package --file pom.xml
          
  publish-job:
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - name: Publishing Job
          uses: actions/checkout@v2
          
          
        - name: Step 1 - Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
            
            
        - name: Step 2 - Creating .JAR file
          run: |
               mvn -B package --file pom.xml -DskipTests
               mkdir staging && cp target/*.jar staging
        
        - name: Step 3 - Uploading Artifact
          uses: actions/upload-artifact@v1
          with:
            name: Package
            path: staging
            
  build-docker-image:
        name: Publish to Docker Hub
        runs-on: ubuntu-latest
        needs: [publish-job]

        steps:
          - uses: actions/checkout@v2
          - name: Login to Docker Hub
            run: docker login -u latifyahia -p maven1234
          - name: Build Container image
            run: docker build -t https://hub.docker.com/repository/docker/latifyahia/maven_ci_cd:latest 
          - name: Publish Docker image
            run: docker push https://hub.docker.com/repository/docker/latifyahia/maven_ci_cd


